### ISSUE TITLE
Feature Request: Add slider-carousel

### ISSUE THREAD

**Issue by eugene-kovaljov** [pluralsight/design-system#491] opened 2019-04-04 20:16 UTC
Currently slider exists in https://app.pluralsight.com/library/ 
It would be great to have something similar in the Design System.
In our own practice we used [Slick](http://kenwheeler.github.io/slick/) slider which works well, but not ideal, especially dots.

**Comment by danethurber** [comment] 2019-04-08 16:20
thanks for the request!

duplicate of #411

**Closed by danethurber** 2019-04-08 16:20 UTC
