### ISSUE TITLE
Dialog: unintended focus on hover

### ISSUE THREAD

**Issue by danethurber** [pluralsight/design-system#927] opened 2020-03-13 20:52 UTC
The Dialog component is focusing the content when it's shown. this is happening during hover events which seems incorrect. This might be a bug and should be explored further

some background here -> https://pluralsight.slack.com/archives/C70HPSJPP/p1581624357160300

**Comment by jaketrent** [comment] 2020-03-13 21:09
I saw the slack thread.  A few things from my mind, and I encourage more team input:

- Focus on mount should happen on 1st mount as well.  If it's only on 2nd+ like Ben indicates, that seems a bug.
- Focus on mount was by design.  The common case for dialog was to have more than text (eg, this is the modal component).  Focus there is good for screenreading and tab order to interactive elements.
- Ben's observation: He's in a case where he wants the experience of a tooltip, but Tooltip only allows strings, so they used Dialog.  This was according to our advice.
- Tooltip was designed as string-only for reasons listed on the ref page and then differentiated from Dialog.  I currently doubt whether Tooltip should only allow strings.  We get this request a lot: I want a Tooltip with more than just strings.  If no one's using it because of that, we just delete Tooltip and make Dialog handle all cases or something like that.  Tooltip also has a blue (appcues-like) appearance.
- What are the a11y guidelines around screenreading tooltips (short contextual text visible on hover/focus)?  If it's to focus, then we should focus tooltips too, and Dialog is doing the right thing, and maybe nothing else needs to change.

**Comment by jaketrent** [comment] 2020-03-23 16:27
Triage: Copy Material UI: Gets and traps focus, no indicator ring, esc to untrap, returns to activating link/button

**Comment by jaketrent** [comment] 2020-03-23 16:35
Short-term: Get rid of focus indicator on Dialog

Long-term: Wait. We need to figure out the diving lines between Tooltip and Dialog, which does what, or if one doesn't need to exist.  This is longer term.  Not going to pick this up atm.  Closing with a 'reopen in the future'.

**Closed** 2020-04-30 17:12 UTC
Labels: enhancement
