### ISSUE TITLE
fix(dropdown): dropdown menu closes on scroll

### ISSUE THREAD

**Issue by oleksandrKariaka** [pluralsight/design-system#1300] opened 2020-10-06 10:34 UTC
## Instructions

- open dropdown menu
- scroll a page 

### Expected behavior

Scroll doesn't affect dropdown menu behavior. 

### Actual behavior

Dropdown menu closes on scroll.

![dropdown](https://user-images.githubusercontent.com/11006541/95190836-8c1d6880-07d8-11eb-9e72-5cf53edc903b.gif)

### Related packages

- dropdown@9.0.5

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v60

**Comment by EdwardIrby** [comment] 2020-10-12 13:50
Should probably give them the option to change this behavior a sort of override.

**Comment by jaketrent** [comment] 2020-10-12 16:38
Team triage: Closing on scroll is by design. We added it explicitly. Was addressing other interaction issues that people were having. When designed, we wanted to match browser behavior. Firefox closes the native dropdown on scroll.  Safari/Chrome scroll lock.  We probably want one of these options. We have chosen one (the existing close-on-scroll), and that's where we're at this point. Closing for now.

**Comment by oleksandrKariaka** [comment] 2020-10-15 08:28
@jaketrent got it, thank you for the answer. Just wanted to point out that for relatively long lists a dropdown with such behavior is not usable. It doesn't have an inner scroll or the ability to scroll a page outside. I assume the example below is self-explanatory.
<img width="614" alt="Screenshot 2020-10-15 at 11 20 56" src="https://user-images.githubusercontent.com/11006541/96097321-79dab300-0ed9-11eb-93d7-97d10e0f17d4.png">

**Comment by jaketrent** [comment] 2020-10-15 15:19
@oleksandrKariaka Thanks for pointing out this scenario!  

@sweeting Will you give a bit more thought to the most desirable UX for this case as it relates to Dropdown, please?

**Comment by sweeting** [comment] 2020-10-15 23:31
@jaketrent After looking at how some other UI libraries handle this, it seems we have a couple of options:

1) Constrain the height of the menu to be 8px from the bottom of the viewport. (See [Adobe Spectrum React Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html#asynchronous-loading))
2) Set a reasonable max height (400px feels pretty good) on the menu and set it `overflow-y: scroll` and give it a custom scrollbar (see [Ant.Design Select](https://ant.design/components/select/#components-select-demo-big-data))

Option 2 feels like it would be less complex than Option 1.

Example of setting the height relative to the bottom of the viewport:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/48542/96195418-f5ecef00-0f09-11eb-8432-824199d7125b.png">

Example of setting a reasonable max-height:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/48542/96195930-5c264180-0f0b-11eb-9bfd-55ca398e5b4a.png">

**Comment by jaketrent** [comment] 2020-10-16 18:17
@sweeting Thanks for the options. It seems like we'll want one of this to accompany our current close-on-scroll functionality so that we cover all scenarios. I'll reopen. We need to triage to decide on a solution.

**Comment by jaketrent** [comment] 2020-10-19 16:18
Team triage: Max-height at 400px, cuz easy peazy.

**Closed** 2020-11-03 08:45 UTC
Labels: bug
