### ISSUE TITLE
drawer: When clicking on a drawer the focus shifts to the entire page

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/design-system#385] opened 2018-12-06 15:56 UTC
### Expected behavior
There are two ways to open a drawer, clicking/entering on the down arrow which performs as expected and clicking on the rest of the drawer's base which gives focus to the page instead of the the drawer or something inside the drawer.

**Comment by jaketrent** [comment] 2018-12-07 17:11
After having spent a bit of time on this, I'm not sure that there's a problem here.  

Importantly, I can't reproduce the "focus is given to the page" occurrence when clicking directly on the Drawer Base in order to toggle the drawer.

More than that, we're not doing *any* focus management here.  Instead, tab order seems to me to be "naturally good", where when the drawer opens, new focusable bits are in the right place to tab to next.  

We have this Drawer in a number of significant UIs that have recently been audited by A360 externally, and they had a few nitpicks, such as the aria-label on the toggle button, which we have addressed, but nothing else, which is another reason to make me believe maybe this is a non-issue.  But then again, maybe there's a usage context here that would allow us to repro the odd page focus issue and see a problem more clearly.

@TravisBumgarner would you mind providing more details or setting up a time for you to walk me through it, please?  Thanks!

**Comment by TravisBumgarner** [comment] 2018-12-11 20:21
We've got a time setup next week for a few hours to mob on accessibility. I'll report back after.

**Comment by jaketrent** [comment] 2018-12-19 15:09
I'm going to close this for now for lack of a way forward.  Travis, if you find problems related to this in the future, please feel free to re-open.

**Closed by jaketrent** 2018-12-19 15:09 UTC
Labels: bug

**Comment by TravisBumgarner** [comment] 2018-12-20 20:45
Sorry, I forgot to follow up, we looked over and everything seems good. 👍
